---
title: "Analysis of ENCEVI 2018"
author: '[Mauricio Hernandez](http://mauricioh2.com)'
date: "`r Sys.Date()`"
subtitle: Electricity Consumption Map
bibliography: energy_mex.bib
---

```{r, include=FALSE}
#Remove all objects from current workspace and call garbage collector
rm(list=ls())
gc()

source("./script/general_setup_functions.R")
```


```{r knitr_init, include=FALSE}
#options(max.print = "75")
opts_chunk$set(echo = TRUE,
	             cache = FALSE,
               prompt = FALSE,
               tidy = FALSE,
               comment = NA,
               message = FALSE,
               warning = FALSE,
               fig.path = 'figures/')
```


```{r setup, include=FALSE}
#Generates the css needed by summarytools
st_css()

#devtools::install_github("ropensci/plotly")
knitr::opts_chunk$set(fig.width = 8, collapse = TRUE)

knitr::knit_hooks$set(output = function(x, options){
  if(!is.null(options$max_height)){
    paste('<pre style = "max-height:',
          options$max_height, 
          ';float: left; width: 910px; overflow-y: auto;">',
          x,
          "</pre>",
          sep = "")
  } else{
    x
  }
})
```


```{r}
#Libraries to build map
if (!require("pacman")) install.packages("pacman")
pacman::p_load(party, magrittr, ggplot2,
               knitr, foreign, mxmaps, openxlsx, 
               viridis, scales, geojsonio, rgdal, 
               rgeos, maptools, ggrepel, sf)
```

**Loading datasets**
</br>This dataset was obtained with the "05_bill_power_calculation.Rmd" file.
```{r}
df_clim_reg<- read.csv("./input/state_climatic_regions.csv", 
                          header = TRUE, na.strings="")

df_cons_state <- read.csv("./output/tables/tbl.mean.cons.state.summer.csv", 
                          header = TRUE, na.strings="")

head(df_clim_reg)
```

```{r}
head(df_cons_state)
```


```{r}
df_cons_state$X <- NULL
df_cons_state <- df_cons_state %>%
  rename(state.name = state.f)

head(df_cons_state)
```

```{r}
# create state code variable as a char
df_clim_reg$state_code <- as.character(df_clim_reg$state.code)
df_clim_reg$state_code[df_clim_reg$state.code < 10] <- paste0('0',df_clim_reg$state.code)

#State names that are different in both dataframe
df_cons_state$state.name[df_cons_state$state.name=="NuevoLeon"] <- "Nuevo Leon"
df_cons_state$state.name[df_cons_state$state.name=="Mexico City"] <- "Ciudad De Mexico"

head(df_clim_reg)
```

```{r}
df_state_merge <- merge(x = df_cons_state[ , c('state.name', 'is.summer1',
                                               'mean_cons_month',
                                               'mean_cons_month_low', 
                                               'mean_cons_month_upp')], 
                      y = df_clim_reg[ , c('state.name', 'state.abr', 
                                           'climatic.region', 'state_code')],
                      by = 'state.name', all.x=TRUE)
df_state_merge
```


```{r}
#load Mexico's map dataset from mxmaps project
data("mxstate.topoJSON")

tmpdir <- tempdir()
# have to use RJSONIO or else the topojson isn't valid
write(RJSONIO::toJSON(mxstate.topoJSON), file.path(tmpdir, "state.topojson"))
states <- topojson_read(file.path(tmpdir, "state.topojson"))

# convert to SpatialPolygonsDataFrame
states <- as_Spatial(states)
states$id
```


```{r}
#Make sure the coordinates of the labels are in the correct order
df_state_merge <- cbind(df_state_merge, 
                        data.frame(lon = coordinates(states[match(df_state_merge$state_code, states$id),])[,1],
                                   lat = coordinates(states[match(df_state_merge$state_code, states$id),])[,2]))
df_state_merge
```
```{r}
#df_state_summer <- df_state_merge[df_state_merge=='Yes']
df_state_merge$value <- df_state_merge$mean_cons_month
df_state_merge$region <- df_state_merge$state_code

df_state_summer <- df_state_merge[ which(df_state_merge$is.summer1 =='Yes'), ]
df_state_nosummer <- df_state_merge[ which(df_state_merge$is.summer1 =='No'), ]
df_state_summer
```

```{r}
plt_cons_summer <- mxstate_choropleth(df_state_summer, num_colors = 1) 
plt_cons_summer <- plt_cons_summer +
  scale_fill_gradientn("kWh", limits= c(0,800), colors = alpha(c(rev(brewer.pal(11, "Spectral"))), alpha = .7)) +
  labs(x = NULL, y = NULL,
       title = "Average Monthly Electricity Consumption per Household in Summer Period, 2017-2018",
       subtitle = "",
       caption = paste("Source: Own eleboration based on data from the",
                       "National Institute of Statistics and Geography (2018)", 
                       sep = "\n"))
plt_cons_summer <- plt_cons_summer +
  theme(plot.title = element_text(size = 12, face = "bold"),
        plot.caption = element_text(size = 9),
        legend.text = element_text(size = 10),
        legend.position = c(0.86, 0.75))

ggsave("./output/fig/map_monthly_consum_summer.png", plot = plt_cons_summer, 
       dpi = 300, height = 8, width = 10, unit = 'in')

plt_cons_summer
```

```{r}
plt_cons_nosummer <- mxstate_choropleth(df_state_nosummer, num_colors = 1) 
plt_cons_nosummer <- plt_cons_nosummer +
  scale_fill_gradientn("kWh", limits= c(0,800), colors = alpha(c(rev(brewer.pal(11, "Spectral"))), alpha = .7)) +
  labs(x = NULL, y = NULL,
       title = "Average Monthly Electricity Consumption in No-Summer Period, 2017-2018",
       subtitle = "",
       caption = paste("Source: Own eleboration based on data from the",
                       "National Institute of Statistics and Geography (2018)", 
                       sep = "\n"))
plt_cons_nosummer <- plt_cons_nosummer +
  theme(plot.title = element_text(size = 12, face = "bold"),
        plot.caption = element_text(size = 9),
        legend.text = element_text(size = 10),
        legend.position = c(0.86, 0.75))

ggsave("./output/fig/map_monthly_consum_nosummer.png", plot = plt_cons_nosummer, 
       dpi = 300, height = 8, width = 10, unit = 'in')

plt_cons_nosummer
```
## Monthly Consumption for both Periods
```{r}
df_cons_state_both <- read.csv("./output/tables/tbl.mean.cons.state.csv", 
                          header = TRUE, na.strings="")

df_clim_reg<- read.csv("./input/state_climatic_regions.csv", 
                          header = TRUE, na.strings="")

head(df_cons_state_both, n=30)
```

```{r}
df_cons_state_both$X <- NULL
df_cons_state_both <- df_cons_state_both %>%
  rename(state.name = state.f)
```


```{r}
# create state code variable as a char
df_clim_reg$state_code <- as.character(df_clim_reg$state.code)
df_clim_reg$state_code[df_clim_reg$state.code < 10] <- paste0('0',df_clim_reg$state.code)

#State names that are different in both dataframe
df_cons_state_both$state.name[df_cons_state_both$state.name=="NuevoLeon"] <- "Nuevo Leon"
df_cons_state_both$state.name[df_cons_state_both$state.name=="Mexico City"] <- "Ciudad De Mexico"

head(df_clim_reg)
```
```{r}
head(df_cons_state_both)
```


```{r}
df_state_merge <- merge(x = df_cons_state_both[ , c('state.name',
                                               'mean_cons_month',
                                               'mean_cons_month_low', 
                                               'mean_cons_month_upp')], 
                      y = df_clim_reg[ , c('state.name', 'state.abr', 
                                           'climatic.region', 'state_code')],
                      by = 'state.name', all.x=TRUE)
df_state_merge
```


```{r}
#df_state_summer <- df_state_merge[df_state_merge=='Yes']
df_state_merge$value <- df_state_merge$mean_cons_month
df_state_merge$region <- df_state_merge$state_code
```

```{r}
plt_cons <- mxstate_choropleth(df_state_merge, num_colors = 1) 
plt_cons <- plt_cons +
  scale_fill_gradientn("kWh", limits= c(0,800), colors = alpha(c(rev(brewer.pal(11, "Spectral"))), alpha = .7)) +
  labs(x = NULL, y = NULL,
       title = "Average Monthly Electricity Consumption per Household, 2017-2018",
       subtitle = "",
       caption = paste("Source: Own eleboration based on data from the",
                       "National Institute of Statistics and Geography (2018)", 
                       sep = "\n"))
plt_cons <- plt_cons +
  theme(plot.title = element_text(size = 14, face = "bold", hjust = .5),
        plot.caption = element_text(size = 10),
        legend.text = element_text(size = 11),
        legend.position = c(0.86, 0.75))

ggsave("./output/fig/map_monthly_consum.png", plot = plt_cons, 
       dpi = 300, height = 8, width = 10, unit = 'in')

plt_cons
```

```{r}
head(df_state_summer)
```

```{r}
head(df_cons_state_both)
```

